# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160206_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'rate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, default=b'', max_length=300, null=True, verbose_name=b'text'),
        ),
    ]
