# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20160206_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name=b'Price'),
        ),
    ]
