# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_task_price'),
        ('catalogue', '0004_myuser_is_admin'),
    ]

    operations = [
    ]
